### ISSUE TITLE
部署的时候遇到了下列错误，文件列表中没有发现./logs文件目录

### ISSUE THREAD

**Issue by loophe** [33357/uniswap-v2-contract#1]
[Error: ENOENT: no such file or directory, open './logs/UniswapV2:deploy.lock']

**Comment by loophe** [comment]
解决了！应该标注以下，需要在根目录里新建一个./logs空文件夹，因为.gitignore文件里屏蔽了这个文件夹。

**Comment by 33357** [comment]
是的，本地需要新建logs文件夹。
